version: 0.2

# Define CodeBuild phases
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"

  build:
    commands:
      - echo "Build step (build and test here)"

  post_build:
    commands:
      - ./deploy.sh

cache:
  paths:
    - '/var/lib/docker'